-- MySQL Script generated by MySQL Workbench
-- 03/30/16 12:39:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema openWall
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema openWall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `openWall` DEFAULT CHARACTER SET utf8 ;
USE `openWall` ;

-- -----------------------------------------------------
-- Table `openWall`.`publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openWall`.`publication` (
  `idpublication` INT NOT NULL AUTO_INCREMENT,
  `text_content` VARCHAR(140) NOT NULL,
  `count` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idpublication`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
